---
- name: "ping main"
  ping:
  register: msg
- debug:
    msg: "{{ msg }} this is main"
  when: '"{{ ENV }} " == "uat" or "{{ ENV }} " == "prod"'

- include_tasks: ping.yml
- include_tasks: ping2.yml